# Generated by Django 6.0.1 on 2026-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_images',
            field=models.ManyToManyField(blank=True, related_name='products_secondary', to='tienda.image'),
        ),
    ]
