# Generated by Django 6.0.1 on 2026-02-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_product_secondary_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='briefdesc',
            field=models.TextField(default=''),
        ),
    ]
