# Generated by Django 6.0.4 on 2026-05-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_add_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='briefdesc',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
