# Generated by Django 6.0.5 on 2026-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_cartitem_quantity_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
