# Generated by Django 6.0.5 on 2026-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_cart_session_key_alter_order_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
