# Generated by Django 6.0.1 on 2026-02-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_ordermessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Texto alternativo'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('address_line_1', models.CharField(max_length=250, verbose_name='Dirección')),
                ('address_line_2', models.CharField(blank=True, max_length=250, verbose_name='Dirección (línea 2)')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de envío',
                'verbose_name_plural': 'Direcciones de envío',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
